# Generated by Django 3.1 on 2021-04-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akt',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
