# Generated by Django 3.1 on 2021-04-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akts', '0002_auto_20210412_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='akt',
            name='created_at',
            field=models.DateTimeField(default='2021-01-01 12:12'),
            preserve_default=False,
        ),
    ]
