# Generated by Django 3.1 on 2021-04-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invent',
            name='act_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
